config/routes.rb
Rails.application.routes.draw do

	mount ActionCable.server => '/cable'
	devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout' }, controllers: { sessions: 'sessions' }
	#get '/login', to: 'sessions#new'
	#post '/login', to: 'sessions#create'
	#delete '/logout', to: 'sessions#destroy'
	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	root to: "rooms#index"
	resources :users
	resources :rooms
	resources :rooms do
		resources :messages
	end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dictionary.rb
class Dictionary < ApplicationRecord

  scope :by_id, -> (id) { where(id: id) }
  scope :by_word, -> (word) { where(word: word) }
end

app/models/message.rb
class Message < ApplicationRecord
	belongs_to :user
	belongs_to :room

	validates :text, presence: true

	after_commit { RoomWorker.perform_async(self.id) }

	scope :by_id, -> (id) { where(id: id) }
	scope :by_room_id, -> (room_id) { where(room_id: room_id) }
	scope :with_user, -> { includes(:user) }
	scope :order_by_creation, -> { order(created_at: :asc) }

	def is_acceptable
		last_message = Message
			.by_room_id(self.room_id)
			.order_by_creation
			.last
	end
end

app/models/online_user.rb
class OnlineUser < ApplicationRecord
end

app/models/room.rb
class Room < ApplicationRecord
	has_many :message
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	has_many :messages

	def appear(page = nil)
		user = get_db_user
		if user
			if !page
				user.first.increment!(:appearances)
			elsif user.page != page
				user.update(page: page)
			end
			user.first.increment!(:appearances)
		else
			OnlineUser.new(user_id: self.id).save
		end
	end

	def disappear
		user = get_db_user
		if user
			#user.first.decrement!(:appearances)
			user.destroy
		end
	end

	def away
		user = get_db_user
		if user
			user.destroy
		end
	end

	def is_online
		if cookies.signed[:user_id] = self.id
			return true
		else
			user = get_db_user
			if user 
				return true
			else
				return false
			end
		end	
	end

	private

	def get_db_user
		user = OnlineUser.find_by(user_id: self.id)
		return user
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def index
    @messages = Message.joins(:user)
  end


  def create
    @new_message = Message.new
    @new_message.attributes = message_params
    @new_message.user_id = current_user.id
    @user = @new_message.user
    @new_message.room_id = params[:room_id]
    @new_message.save
    render layout: false
  end

  private
  def message_params
    params.require(:message).permit(:text)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
	before_action :authenticate_user!
	layout "chatroom", only: :show

	def index
		@rooms = Room.all
	end

	def show
		room_id = params[:id]
		@room = Room.find(room_id)
		@messages = Message.by_room_id(room_id).order_by_creation.with_user
		@new_message = Message.new
	end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
  layout "login", only: :new

  def create
    logger.debug "USER ID: #{current_user.id}"
    cookies.signed[:user_id] = current_user.id
    super
  end

  def destroy
    cookies.delete :user_id
    super
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		@users = User.all
	end

	def new
	end

	def show
		@user = User.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_body.html.erb
<div class="app-body">
	<%= yield %>
</div>

app/views/layouts/_header.html.erb
<header>
	<% if current_user %>
		<%= link_to 'Log out', 
			destroy_user_session_path, 
			class: "header-button login-out",
			method: :delete %>
		<%= link_to 'Rooms', 
			rooms_path, 
			class: "header-button" %>
	<% else %>
		<%= link_to 'Log in',
			new_user_session_path,
			class: "header-button login-out" %>
	<% end %>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
	  <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
	  <%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>

app/views/layouts/chatroom.html.erb
<!DOCTYPE html>
<html>
  <head>
	  <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'general', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'chatroom', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
	  <%= render 'layouts/header' %>
	  <%= render 'layouts/body' %>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="chat-message">
	<h5 class="message-created-at"><%= l message.created_at, format: :time_only %></h5>&nbsp;
	<h5 class="message-username">
		<%= link_to message.user.username, 
			controller: "users", 
			action: "show", 
			id: message.user_id %>
</h5>
	<h3 class="message-text"><%= message.text %></h3>
</div>

app/views/messages/index.html.erb
<h2> Some messages </h2>

<% @messages.each do |message| %>
	<h4><b>message: </b> <%= message.text %></h4>
	<h5><b>username: </b> <%= message.user.username %></h5>
<% end %>

app/views/rooms/index.html.erb
<%= content_for :title, "Rooms" %>
<h2> Some rooms </h2>

<% @rooms.each do |room| %>
	<h4>
		<a href="/rooms/<%= room.id %>">
			<%= room.name %>
		</a>
	</h4>
<% end %>

app/views/rooms/show.html.erb
<%= content_for :title, "##{params[:id]} room" %>
<%= javascript_include_tag :messages %>
<%= hidden_field_tag('room-id', params[:id]) %>

<h3 class="room-name">This is room <%= @room.id %> with name "<%= @room.name %>"</h3>
<%#<h1><%= Rails.env </h1>%>

<div class="messages-container">
	<%= render @messages %>
</div>

<%= form_for (@new_message), remote: true, url: room_messages_path(params[:id]), html: { class: "message-form"} do |form| %>
	<%= form.text_area :text, class: "message-area" %>
	<%= form.submit "Send", class: "message-submit" %>
<% end %>

app/views/users/index.html.erb
<h2> Some users </h2>

<% @users.each do |user| %>
	<h4><b>User: </b> <%= user.username %></h4>
<% end %>

app/views/users/show.html.erb
<% content_for :title, "#{@user.username}" %>
Username: <%= @user.username %>